/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UcretsizAsoAraclariRouteImport } from './routes/ucretsiz-aso-araclari'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardStoreRouteImport } from './routes/dashboard.store'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard.reviews'
import { Route as DashboardMarketsRouteImport } from './routes/dashboard.markets'
import { Route as DashboardKeywordsRouteImport } from './routes/dashboard.keywords'
import { Route as DashboardHelpRouteImport } from './routes/dashboard.help'
import { Route as DashboardCreativeRouteImport } from './routes/dashboard.creative'
import { Route as DashboardCompetitorsRouteImport } from './routes/dashboard.competitors'
import { Route as DashboardAiRouteImport } from './routes/dashboard.ai'
import { Route as DashboardStoreIndexRouteImport } from './routes/dashboard.store.index'
import { Route as DashboardReviewsIndexRouteImport } from './routes/dashboard.reviews.index'
import { Route as DashboardMarketsIndexRouteImport } from './routes/dashboard.markets.index'
import { Route as DashboardKeywordsIndexRouteImport } from './routes/dashboard.keywords.index'
import { Route as DashboardCreativeIndexRouteImport } from './routes/dashboard.creative.index'
import { Route as DashboardCompetitorsIndexRouteImport } from './routes/dashboard.competitors.index'
import { Route as DashboardAiIndexRouteImport } from './routes/dashboard.ai.index'
import { Route as DashboardStorePublishingRouteImport } from './routes/dashboard.store.publishing'
import { Route as DashboardStoreLocalizationRouteImport } from './routes/dashboard.store.localization'
import { Route as DashboardStoreListingRouteImport } from './routes/dashboard.store.listing'
import { Route as DashboardStoreEventsRouteImport } from './routes/dashboard.store.events'
import { Route as DashboardStoreCreativesRouteImport } from './routes/dashboard.store.creatives'
import { Route as DashboardReviewsSentimentRouteImport } from './routes/dashboard.reviews.sentiment'
import { Route as DashboardReviewsRequestsRouteImport } from './routes/dashboard.reviews.requests'
import { Route as DashboardReviewsCompetitorsRouteImport } from './routes/dashboard.reviews.competitors'
import { Route as DashboardMarketsRisingRouteImport } from './routes/dashboard.markets.rising'
import { Route as DashboardMarketsOpportunitiesRouteImport } from './routes/dashboard.markets.opportunities'
import { Route as DashboardMarketsComparisonRouteImport } from './routes/dashboard.markets.comparison'
import { Route as DashboardKeywordsTrackedRouteImport } from './routes/dashboard.keywords.tracked'
import { Route as DashboardKeywordsResearchRouteImport } from './routes/dashboard.keywords.research'
import { Route as DashboardKeywordsMovementsRouteImport } from './routes/dashboard.keywords.movements'
import { Route as DashboardKeywordsCompetitorsRouteImport } from './routes/dashboard.keywords.competitors'
import { Route as DashboardCreativeCompetitorsRouteImport } from './routes/dashboard.creative.competitors'
import { Route as DashboardCreativeComparisonRouteImport } from './routes/dashboard.creative.comparison'
import { Route as DashboardCreativeChangesRouteImport } from './routes/dashboard.creative.changes'
import { Route as DashboardCompetitorsVisibilityRouteImport } from './routes/dashboard.competitors.visibility'
import { Route as DashboardCompetitorsChangesRouteImport } from './routes/dashboard.competitors.changes'
import { Route as DashboardCompetitorsAppsRouteImport } from './routes/dashboard.competitors.apps'
import { Route as DashboardAiSavedRouteImport } from './routes/dashboard.ai.saved'
import { Route as DashboardKeywordsInspectKeywordRouteImport } from './routes/dashboard.keywords.inspect.$keyword'

const UcretsizAsoAraclariRoute = UcretsizAsoAraclariRouteImport.update({
  id: '/ucretsiz-aso-araclari',
  path: '/ucretsiz-aso-araclari',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStoreRoute = DashboardStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketsRoute = DashboardMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKeywordsRoute = DashboardKeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHelpRoute = DashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCreativeRoute = DashboardCreativeRouteImport.update({
  id: '/creative',
  path: '/creative',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCompetitorsRoute = DashboardCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiRoute = DashboardAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStoreIndexRoute = DashboardStoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardStoreRoute,
} as any)
const DashboardReviewsIndexRoute = DashboardReviewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardReviewsRoute,
} as any)
const DashboardMarketsIndexRoute = DashboardMarketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardMarketsRoute,
} as any)
const DashboardKeywordsIndexRoute = DashboardKeywordsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardKeywordsRoute,
} as any)
const DashboardCreativeIndexRoute = DashboardCreativeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCreativeRoute,
} as any)
const DashboardCompetitorsIndexRoute =
  DashboardCompetitorsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardCompetitorsRoute,
  } as any)
const DashboardAiIndexRoute = DashboardAiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAiRoute,
} as any)
const DashboardStorePublishingRoute =
  DashboardStorePublishingRouteImport.update({
    id: '/publishing',
    path: '/publishing',
    getParentRoute: () => DashboardStoreRoute,
  } as any)
const DashboardStoreLocalizationRoute =
  DashboardStoreLocalizationRouteImport.update({
    id: '/localization',
    path: '/localization',
    getParentRoute: () => DashboardStoreRoute,
  } as any)
const DashboardStoreListingRoute = DashboardStoreListingRouteImport.update({
  id: '/listing',
  path: '/listing',
  getParentRoute: () => DashboardStoreRoute,
} as any)
const DashboardStoreEventsRoute = DashboardStoreEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardStoreRoute,
} as any)
const DashboardStoreCreativesRoute = DashboardStoreCreativesRouteImport.update({
  id: '/creatives',
  path: '/creatives',
  getParentRoute: () => DashboardStoreRoute,
} as any)
const DashboardReviewsSentimentRoute =
  DashboardReviewsSentimentRouteImport.update({
    id: '/sentiment',
    path: '/sentiment',
    getParentRoute: () => DashboardReviewsRoute,
  } as any)
const DashboardReviewsRequestsRoute =
  DashboardReviewsRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => DashboardReviewsRoute,
  } as any)
const DashboardReviewsCompetitorsRoute =
  DashboardReviewsCompetitorsRouteImport.update({
    id: '/competitors',
    path: '/competitors',
    getParentRoute: () => DashboardReviewsRoute,
  } as any)
const DashboardMarketsRisingRoute = DashboardMarketsRisingRouteImport.update({
  id: '/rising',
  path: '/rising',
  getParentRoute: () => DashboardMarketsRoute,
} as any)
const DashboardMarketsOpportunitiesRoute =
  DashboardMarketsOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => DashboardMarketsRoute,
  } as any)
const DashboardMarketsComparisonRoute =
  DashboardMarketsComparisonRouteImport.update({
    id: '/comparison',
    path: '/comparison',
    getParentRoute: () => DashboardMarketsRoute,
  } as any)
const DashboardKeywordsTrackedRoute =
  DashboardKeywordsTrackedRouteImport.update({
    id: '/tracked',
    path: '/tracked',
    getParentRoute: () => DashboardKeywordsRoute,
  } as any)
const DashboardKeywordsResearchRoute =
  DashboardKeywordsResearchRouteImport.update({
    id: '/research',
    path: '/research',
    getParentRoute: () => DashboardKeywordsRoute,
  } as any)
const DashboardKeywordsMovementsRoute =
  DashboardKeywordsMovementsRouteImport.update({
    id: '/movements',
    path: '/movements',
    getParentRoute: () => DashboardKeywordsRoute,
  } as any)
const DashboardKeywordsCompetitorsRoute =
  DashboardKeywordsCompetitorsRouteImport.update({
    id: '/competitors',
    path: '/competitors',
    getParentRoute: () => DashboardKeywordsRoute,
  } as any)
const DashboardCreativeCompetitorsRoute =
  DashboardCreativeCompetitorsRouteImport.update({
    id: '/competitors',
    path: '/competitors',
    getParentRoute: () => DashboardCreativeRoute,
  } as any)
const DashboardCreativeComparisonRoute =
  DashboardCreativeComparisonRouteImport.update({
    id: '/comparison',
    path: '/comparison',
    getParentRoute: () => DashboardCreativeRoute,
  } as any)
const DashboardCreativeChangesRoute =
  DashboardCreativeChangesRouteImport.update({
    id: '/changes',
    path: '/changes',
    getParentRoute: () => DashboardCreativeRoute,
  } as any)
const DashboardCompetitorsVisibilityRoute =
  DashboardCompetitorsVisibilityRouteImport.update({
    id: '/visibility',
    path: '/visibility',
    getParentRoute: () => DashboardCompetitorsRoute,
  } as any)
const DashboardCompetitorsChangesRoute =
  DashboardCompetitorsChangesRouteImport.update({
    id: '/changes',
    path: '/changes',
    getParentRoute: () => DashboardCompetitorsRoute,
  } as any)
const DashboardCompetitorsAppsRoute =
  DashboardCompetitorsAppsRouteImport.update({
    id: '/apps',
    path: '/apps',
    getParentRoute: () => DashboardCompetitorsRoute,
  } as any)
const DashboardAiSavedRoute = DashboardAiSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => DashboardAiRoute,
} as any)
const DashboardKeywordsInspectKeywordRoute =
  DashboardKeywordsInspectKeywordRouteImport.update({
    id: '/inspect/$keyword',
    path: '/inspect/$keyword',
    getParentRoute: () => DashboardKeywordsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/ucretsiz-aso-araclari': typeof UcretsizAsoAraclariRoute
  '/dashboard/ai': typeof DashboardAiRouteWithChildren
  '/dashboard/competitors': typeof DashboardCompetitorsRouteWithChildren
  '/dashboard/creative': typeof DashboardCreativeRouteWithChildren
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/keywords': typeof DashboardKeywordsRouteWithChildren
  '/dashboard/markets': typeof DashboardMarketsRouteWithChildren
  '/dashboard/reviews': typeof DashboardReviewsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/store': typeof DashboardStoreRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/ai/saved': typeof DashboardAiSavedRoute
  '/dashboard/competitors/apps': typeof DashboardCompetitorsAppsRoute
  '/dashboard/competitors/changes': typeof DashboardCompetitorsChangesRoute
  '/dashboard/competitors/visibility': typeof DashboardCompetitorsVisibilityRoute
  '/dashboard/creative/changes': typeof DashboardCreativeChangesRoute
  '/dashboard/creative/comparison': typeof DashboardCreativeComparisonRoute
  '/dashboard/creative/competitors': typeof DashboardCreativeCompetitorsRoute
  '/dashboard/keywords/competitors': typeof DashboardKeywordsCompetitorsRoute
  '/dashboard/keywords/movements': typeof DashboardKeywordsMovementsRoute
  '/dashboard/keywords/research': typeof DashboardKeywordsResearchRoute
  '/dashboard/keywords/tracked': typeof DashboardKeywordsTrackedRoute
  '/dashboard/markets/comparison': typeof DashboardMarketsComparisonRoute
  '/dashboard/markets/opportunities': typeof DashboardMarketsOpportunitiesRoute
  '/dashboard/markets/rising': typeof DashboardMarketsRisingRoute
  '/dashboard/reviews/competitors': typeof DashboardReviewsCompetitorsRoute
  '/dashboard/reviews/requests': typeof DashboardReviewsRequestsRoute
  '/dashboard/reviews/sentiment': typeof DashboardReviewsSentimentRoute
  '/dashboard/store/creatives': typeof DashboardStoreCreativesRoute
  '/dashboard/store/events': typeof DashboardStoreEventsRoute
  '/dashboard/store/listing': typeof DashboardStoreListingRoute
  '/dashboard/store/localization': typeof DashboardStoreLocalizationRoute
  '/dashboard/store/publishing': typeof DashboardStorePublishingRoute
  '/dashboard/ai/': typeof DashboardAiIndexRoute
  '/dashboard/competitors/': typeof DashboardCompetitorsIndexRoute
  '/dashboard/creative/': typeof DashboardCreativeIndexRoute
  '/dashboard/keywords/': typeof DashboardKeywordsIndexRoute
  '/dashboard/markets/': typeof DashboardMarketsIndexRoute
  '/dashboard/reviews/': typeof DashboardReviewsIndexRoute
  '/dashboard/store/': typeof DashboardStoreIndexRoute
  '/dashboard/keywords/inspect/$keyword': typeof DashboardKeywordsInspectKeywordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ucretsiz-aso-araclari': typeof UcretsizAsoAraclariRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/ai/saved': typeof DashboardAiSavedRoute
  '/dashboard/competitors/apps': typeof DashboardCompetitorsAppsRoute
  '/dashboard/competitors/changes': typeof DashboardCompetitorsChangesRoute
  '/dashboard/competitors/visibility': typeof DashboardCompetitorsVisibilityRoute
  '/dashboard/creative/changes': typeof DashboardCreativeChangesRoute
  '/dashboard/creative/comparison': typeof DashboardCreativeComparisonRoute
  '/dashboard/creative/competitors': typeof DashboardCreativeCompetitorsRoute
  '/dashboard/keywords/competitors': typeof DashboardKeywordsCompetitorsRoute
  '/dashboard/keywords/movements': typeof DashboardKeywordsMovementsRoute
  '/dashboard/keywords/research': typeof DashboardKeywordsResearchRoute
  '/dashboard/keywords/tracked': typeof DashboardKeywordsTrackedRoute
  '/dashboard/markets/comparison': typeof DashboardMarketsComparisonRoute
  '/dashboard/markets/opportunities': typeof DashboardMarketsOpportunitiesRoute
  '/dashboard/markets/rising': typeof DashboardMarketsRisingRoute
  '/dashboard/reviews/competitors': typeof DashboardReviewsCompetitorsRoute
  '/dashboard/reviews/requests': typeof DashboardReviewsRequestsRoute
  '/dashboard/reviews/sentiment': typeof DashboardReviewsSentimentRoute
  '/dashboard/store/creatives': typeof DashboardStoreCreativesRoute
  '/dashboard/store/events': typeof DashboardStoreEventsRoute
  '/dashboard/store/listing': typeof DashboardStoreListingRoute
  '/dashboard/store/localization': typeof DashboardStoreLocalizationRoute
  '/dashboard/store/publishing': typeof DashboardStorePublishingRoute
  '/dashboard/ai': typeof DashboardAiIndexRoute
  '/dashboard/competitors': typeof DashboardCompetitorsIndexRoute
  '/dashboard/creative': typeof DashboardCreativeIndexRoute
  '/dashboard/keywords': typeof DashboardKeywordsIndexRoute
  '/dashboard/markets': typeof DashboardMarketsIndexRoute
  '/dashboard/reviews': typeof DashboardReviewsIndexRoute
  '/dashboard/store': typeof DashboardStoreIndexRoute
  '/dashboard/keywords/inspect/$keyword': typeof DashboardKeywordsInspectKeywordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/ucretsiz-aso-araclari': typeof UcretsizAsoAraclariRoute
  '/dashboard/ai': typeof DashboardAiRouteWithChildren
  '/dashboard/competitors': typeof DashboardCompetitorsRouteWithChildren
  '/dashboard/creative': typeof DashboardCreativeRouteWithChildren
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/keywords': typeof DashboardKeywordsRouteWithChildren
  '/dashboard/markets': typeof DashboardMarketsRouteWithChildren
  '/dashboard/reviews': typeof DashboardReviewsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/store': typeof DashboardStoreRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/ai/saved': typeof DashboardAiSavedRoute
  '/dashboard/competitors/apps': typeof DashboardCompetitorsAppsRoute
  '/dashboard/competitors/changes': typeof DashboardCompetitorsChangesRoute
  '/dashboard/competitors/visibility': typeof DashboardCompetitorsVisibilityRoute
  '/dashboard/creative/changes': typeof DashboardCreativeChangesRoute
  '/dashboard/creative/comparison': typeof DashboardCreativeComparisonRoute
  '/dashboard/creative/competitors': typeof DashboardCreativeCompetitorsRoute
  '/dashboard/keywords/competitors': typeof DashboardKeywordsCompetitorsRoute
  '/dashboard/keywords/movements': typeof DashboardKeywordsMovementsRoute
  '/dashboard/keywords/research': typeof DashboardKeywordsResearchRoute
  '/dashboard/keywords/tracked': typeof DashboardKeywordsTrackedRoute
  '/dashboard/markets/comparison': typeof DashboardMarketsComparisonRoute
  '/dashboard/markets/opportunities': typeof DashboardMarketsOpportunitiesRoute
  '/dashboard/markets/rising': typeof DashboardMarketsRisingRoute
  '/dashboard/reviews/competitors': typeof DashboardReviewsCompetitorsRoute
  '/dashboard/reviews/requests': typeof DashboardReviewsRequestsRoute
  '/dashboard/reviews/sentiment': typeof DashboardReviewsSentimentRoute
  '/dashboard/store/creatives': typeof DashboardStoreCreativesRoute
  '/dashboard/store/events': typeof DashboardStoreEventsRoute
  '/dashboard/store/listing': typeof DashboardStoreListingRoute
  '/dashboard/store/localization': typeof DashboardStoreLocalizationRoute
  '/dashboard/store/publishing': typeof DashboardStorePublishingRoute
  '/dashboard/ai/': typeof DashboardAiIndexRoute
  '/dashboard/competitors/': typeof DashboardCompetitorsIndexRoute
  '/dashboard/creative/': typeof DashboardCreativeIndexRoute
  '/dashboard/keywords/': typeof DashboardKeywordsIndexRoute
  '/dashboard/markets/': typeof DashboardMarketsIndexRoute
  '/dashboard/reviews/': typeof DashboardReviewsIndexRoute
  '/dashboard/store/': typeof DashboardStoreIndexRoute
  '/dashboard/keywords/inspect/$keyword': typeof DashboardKeywordsInspectKeywordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/ucretsiz-aso-araclari'
    | '/dashboard/ai'
    | '/dashboard/competitors'
    | '/dashboard/creative'
    | '/dashboard/help'
    | '/dashboard/keywords'
    | '/dashboard/markets'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/store'
    | '/dashboard/'
    | '/dashboard/ai/saved'
    | '/dashboard/competitors/apps'
    | '/dashboard/competitors/changes'
    | '/dashboard/competitors/visibility'
    | '/dashboard/creative/changes'
    | '/dashboard/creative/comparison'
    | '/dashboard/creative/competitors'
    | '/dashboard/keywords/competitors'
    | '/dashboard/keywords/movements'
    | '/dashboard/keywords/research'
    | '/dashboard/keywords/tracked'
    | '/dashboard/markets/comparison'
    | '/dashboard/markets/opportunities'
    | '/dashboard/markets/rising'
    | '/dashboard/reviews/competitors'
    | '/dashboard/reviews/requests'
    | '/dashboard/reviews/sentiment'
    | '/dashboard/store/creatives'
    | '/dashboard/store/events'
    | '/dashboard/store/listing'
    | '/dashboard/store/localization'
    | '/dashboard/store/publishing'
    | '/dashboard/ai/'
    | '/dashboard/competitors/'
    | '/dashboard/creative/'
    | '/dashboard/keywords/'
    | '/dashboard/markets/'
    | '/dashboard/reviews/'
    | '/dashboard/store/'
    | '/dashboard/keywords/inspect/$keyword'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ucretsiz-aso-araclari'
    | '/dashboard/help'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/ai/saved'
    | '/dashboard/competitors/apps'
    | '/dashboard/competitors/changes'
    | '/dashboard/competitors/visibility'
    | '/dashboard/creative/changes'
    | '/dashboard/creative/comparison'
    | '/dashboard/creative/competitors'
    | '/dashboard/keywords/competitors'
    | '/dashboard/keywords/movements'
    | '/dashboard/keywords/research'
    | '/dashboard/keywords/tracked'
    | '/dashboard/markets/comparison'
    | '/dashboard/markets/opportunities'
    | '/dashboard/markets/rising'
    | '/dashboard/reviews/competitors'
    | '/dashboard/reviews/requests'
    | '/dashboard/reviews/sentiment'
    | '/dashboard/store/creatives'
    | '/dashboard/store/events'
    | '/dashboard/store/listing'
    | '/dashboard/store/localization'
    | '/dashboard/store/publishing'
    | '/dashboard/ai'
    | '/dashboard/competitors'
    | '/dashboard/creative'
    | '/dashboard/keywords'
    | '/dashboard/markets'
    | '/dashboard/reviews'
    | '/dashboard/store'
    | '/dashboard/keywords/inspect/$keyword'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/ucretsiz-aso-araclari'
    | '/dashboard/ai'
    | '/dashboard/competitors'
    | '/dashboard/creative'
    | '/dashboard/help'
    | '/dashboard/keywords'
    | '/dashboard/markets'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/store'
    | '/dashboard/'
    | '/dashboard/ai/saved'
    | '/dashboard/competitors/apps'
    | '/dashboard/competitors/changes'
    | '/dashboard/competitors/visibility'
    | '/dashboard/creative/changes'
    | '/dashboard/creative/comparison'
    | '/dashboard/creative/competitors'
    | '/dashboard/keywords/competitors'
    | '/dashboard/keywords/movements'
    | '/dashboard/keywords/research'
    | '/dashboard/keywords/tracked'
    | '/dashboard/markets/comparison'
    | '/dashboard/markets/opportunities'
    | '/dashboard/markets/rising'
    | '/dashboard/reviews/competitors'
    | '/dashboard/reviews/requests'
    | '/dashboard/reviews/sentiment'
    | '/dashboard/store/creatives'
    | '/dashboard/store/events'
    | '/dashboard/store/listing'
    | '/dashboard/store/localization'
    | '/dashboard/store/publishing'
    | '/dashboard/ai/'
    | '/dashboard/competitors/'
    | '/dashboard/creative/'
    | '/dashboard/keywords/'
    | '/dashboard/markets/'
    | '/dashboard/reviews/'
    | '/dashboard/store/'
    | '/dashboard/keywords/inspect/$keyword'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  UcretsizAsoAraclariRoute: typeof UcretsizAsoAraclariRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ucretsiz-aso-araclari': {
      id: '/ucretsiz-aso-araclari'
      path: '/ucretsiz-aso-araclari'
      fullPath: '/ucretsiz-aso-araclari'
      preLoaderRoute: typeof UcretsizAsoAraclariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/store': {
      id: '/dashboard/store'
      path: '/store'
      fullPath: '/dashboard/store'
      preLoaderRoute: typeof DashboardStoreRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/markets': {
      id: '/dashboard/markets'
      path: '/markets'
      fullPath: '/dashboard/markets'
      preLoaderRoute: typeof DashboardMarketsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/keywords': {
      id: '/dashboard/keywords'
      path: '/keywords'
      fullPath: '/dashboard/keywords'
      preLoaderRoute: typeof DashboardKeywordsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/help': {
      id: '/dashboard/help'
      path: '/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof DashboardHelpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/creative': {
      id: '/dashboard/creative'
      path: '/creative'
      fullPath: '/dashboard/creative'
      preLoaderRoute: typeof DashboardCreativeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/competitors': {
      id: '/dashboard/competitors'
      path: '/competitors'
      fullPath: '/dashboard/competitors'
      preLoaderRoute: typeof DashboardCompetitorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai': {
      id: '/dashboard/ai'
      path: '/ai'
      fullPath: '/dashboard/ai'
      preLoaderRoute: typeof DashboardAiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/store/': {
      id: '/dashboard/store/'
      path: '/'
      fullPath: '/dashboard/store/'
      preLoaderRoute: typeof DashboardStoreIndexRouteImport
      parentRoute: typeof DashboardStoreRoute
    }
    '/dashboard/reviews/': {
      id: '/dashboard/reviews/'
      path: '/'
      fullPath: '/dashboard/reviews/'
      preLoaderRoute: typeof DashboardReviewsIndexRouteImport
      parentRoute: typeof DashboardReviewsRoute
    }
    '/dashboard/markets/': {
      id: '/dashboard/markets/'
      path: '/'
      fullPath: '/dashboard/markets/'
      preLoaderRoute: typeof DashboardMarketsIndexRouteImport
      parentRoute: typeof DashboardMarketsRoute
    }
    '/dashboard/keywords/': {
      id: '/dashboard/keywords/'
      path: '/'
      fullPath: '/dashboard/keywords/'
      preLoaderRoute: typeof DashboardKeywordsIndexRouteImport
      parentRoute: typeof DashboardKeywordsRoute
    }
    '/dashboard/creative/': {
      id: '/dashboard/creative/'
      path: '/'
      fullPath: '/dashboard/creative/'
      preLoaderRoute: typeof DashboardCreativeIndexRouteImport
      parentRoute: typeof DashboardCreativeRoute
    }
    '/dashboard/competitors/': {
      id: '/dashboard/competitors/'
      path: '/'
      fullPath: '/dashboard/competitors/'
      preLoaderRoute: typeof DashboardCompetitorsIndexRouteImport
      parentRoute: typeof DashboardCompetitorsRoute
    }
    '/dashboard/ai/': {
      id: '/dashboard/ai/'
      path: '/'
      fullPath: '/dashboard/ai/'
      preLoaderRoute: typeof DashboardAiIndexRouteImport
      parentRoute: typeof DashboardAiRoute
    }
    '/dashboard/store/publishing': {
      id: '/dashboard/store/publishing'
      path: '/publishing'
      fullPath: '/dashboard/store/publishing'
      preLoaderRoute: typeof DashboardStorePublishingRouteImport
      parentRoute: typeof DashboardStoreRoute
    }
    '/dashboard/store/localization': {
      id: '/dashboard/store/localization'
      path: '/localization'
      fullPath: '/dashboard/store/localization'
      preLoaderRoute: typeof DashboardStoreLocalizationRouteImport
      parentRoute: typeof DashboardStoreRoute
    }
    '/dashboard/store/listing': {
      id: '/dashboard/store/listing'
      path: '/listing'
      fullPath: '/dashboard/store/listing'
      preLoaderRoute: typeof DashboardStoreListingRouteImport
      parentRoute: typeof DashboardStoreRoute
    }
    '/dashboard/store/events': {
      id: '/dashboard/store/events'
      path: '/events'
      fullPath: '/dashboard/store/events'
      preLoaderRoute: typeof DashboardStoreEventsRouteImport
      parentRoute: typeof DashboardStoreRoute
    }
    '/dashboard/store/creatives': {
      id: '/dashboard/store/creatives'
      path: '/creatives'
      fullPath: '/dashboard/store/creatives'
      preLoaderRoute: typeof DashboardStoreCreativesRouteImport
      parentRoute: typeof DashboardStoreRoute
    }
    '/dashboard/reviews/sentiment': {
      id: '/dashboard/reviews/sentiment'
      path: '/sentiment'
      fullPath: '/dashboard/reviews/sentiment'
      preLoaderRoute: typeof DashboardReviewsSentimentRouteImport
      parentRoute: typeof DashboardReviewsRoute
    }
    '/dashboard/reviews/requests': {
      id: '/dashboard/reviews/requests'
      path: '/requests'
      fullPath: '/dashboard/reviews/requests'
      preLoaderRoute: typeof DashboardReviewsRequestsRouteImport
      parentRoute: typeof DashboardReviewsRoute
    }
    '/dashboard/reviews/competitors': {
      id: '/dashboard/reviews/competitors'
      path: '/competitors'
      fullPath: '/dashboard/reviews/competitors'
      preLoaderRoute: typeof DashboardReviewsCompetitorsRouteImport
      parentRoute: typeof DashboardReviewsRoute
    }
    '/dashboard/markets/rising': {
      id: '/dashboard/markets/rising'
      path: '/rising'
      fullPath: '/dashboard/markets/rising'
      preLoaderRoute: typeof DashboardMarketsRisingRouteImport
      parentRoute: typeof DashboardMarketsRoute
    }
    '/dashboard/markets/opportunities': {
      id: '/dashboard/markets/opportunities'
      path: '/opportunities'
      fullPath: '/dashboard/markets/opportunities'
      preLoaderRoute: typeof DashboardMarketsOpportunitiesRouteImport
      parentRoute: typeof DashboardMarketsRoute
    }
    '/dashboard/markets/comparison': {
      id: '/dashboard/markets/comparison'
      path: '/comparison'
      fullPath: '/dashboard/markets/comparison'
      preLoaderRoute: typeof DashboardMarketsComparisonRouteImport
      parentRoute: typeof DashboardMarketsRoute
    }
    '/dashboard/keywords/tracked': {
      id: '/dashboard/keywords/tracked'
      path: '/tracked'
      fullPath: '/dashboard/keywords/tracked'
      preLoaderRoute: typeof DashboardKeywordsTrackedRouteImport
      parentRoute: typeof DashboardKeywordsRoute
    }
    '/dashboard/keywords/research': {
      id: '/dashboard/keywords/research'
      path: '/research'
      fullPath: '/dashboard/keywords/research'
      preLoaderRoute: typeof DashboardKeywordsResearchRouteImport
      parentRoute: typeof DashboardKeywordsRoute
    }
    '/dashboard/keywords/movements': {
      id: '/dashboard/keywords/movements'
      path: '/movements'
      fullPath: '/dashboard/keywords/movements'
      preLoaderRoute: typeof DashboardKeywordsMovementsRouteImport
      parentRoute: typeof DashboardKeywordsRoute
    }
    '/dashboard/keywords/competitors': {
      id: '/dashboard/keywords/competitors'
      path: '/competitors'
      fullPath: '/dashboard/keywords/competitors'
      preLoaderRoute: typeof DashboardKeywordsCompetitorsRouteImport
      parentRoute: typeof DashboardKeywordsRoute
    }
    '/dashboard/creative/competitors': {
      id: '/dashboard/creative/competitors'
      path: '/competitors'
      fullPath: '/dashboard/creative/competitors'
      preLoaderRoute: typeof DashboardCreativeCompetitorsRouteImport
      parentRoute: typeof DashboardCreativeRoute
    }
    '/dashboard/creative/comparison': {
      id: '/dashboard/creative/comparison'
      path: '/comparison'
      fullPath: '/dashboard/creative/comparison'
      preLoaderRoute: typeof DashboardCreativeComparisonRouteImport
      parentRoute: typeof DashboardCreativeRoute
    }
    '/dashboard/creative/changes': {
      id: '/dashboard/creative/changes'
      path: '/changes'
      fullPath: '/dashboard/creative/changes'
      preLoaderRoute: typeof DashboardCreativeChangesRouteImport
      parentRoute: typeof DashboardCreativeRoute
    }
    '/dashboard/competitors/visibility': {
      id: '/dashboard/competitors/visibility'
      path: '/visibility'
      fullPath: '/dashboard/competitors/visibility'
      preLoaderRoute: typeof DashboardCompetitorsVisibilityRouteImport
      parentRoute: typeof DashboardCompetitorsRoute
    }
    '/dashboard/competitors/changes': {
      id: '/dashboard/competitors/changes'
      path: '/changes'
      fullPath: '/dashboard/competitors/changes'
      preLoaderRoute: typeof DashboardCompetitorsChangesRouteImport
      parentRoute: typeof DashboardCompetitorsRoute
    }
    '/dashboard/competitors/apps': {
      id: '/dashboard/competitors/apps'
      path: '/apps'
      fullPath: '/dashboard/competitors/apps'
      preLoaderRoute: typeof DashboardCompetitorsAppsRouteImport
      parentRoute: typeof DashboardCompetitorsRoute
    }
    '/dashboard/ai/saved': {
      id: '/dashboard/ai/saved'
      path: '/saved'
      fullPath: '/dashboard/ai/saved'
      preLoaderRoute: typeof DashboardAiSavedRouteImport
      parentRoute: typeof DashboardAiRoute
    }
    '/dashboard/keywords/inspect/$keyword': {
      id: '/dashboard/keywords/inspect/$keyword'
      path: '/inspect/$keyword'
      fullPath: '/dashboard/keywords/inspect/$keyword'
      preLoaderRoute: typeof DashboardKeywordsInspectKeywordRouteImport
      parentRoute: typeof DashboardKeywordsRoute
    }
  }
}

interface DashboardAiRouteChildren {
  DashboardAiSavedRoute: typeof DashboardAiSavedRoute
  DashboardAiIndexRoute: typeof DashboardAiIndexRoute
}

const DashboardAiRouteChildren: DashboardAiRouteChildren = {
  DashboardAiSavedRoute: DashboardAiSavedRoute,
  DashboardAiIndexRoute: DashboardAiIndexRoute,
}

const DashboardAiRouteWithChildren = DashboardAiRoute._addFileChildren(
  DashboardAiRouteChildren,
)

interface DashboardCompetitorsRouteChildren {
  DashboardCompetitorsAppsRoute: typeof DashboardCompetitorsAppsRoute
  DashboardCompetitorsChangesRoute: typeof DashboardCompetitorsChangesRoute
  DashboardCompetitorsVisibilityRoute: typeof DashboardCompetitorsVisibilityRoute
  DashboardCompetitorsIndexRoute: typeof DashboardCompetitorsIndexRoute
}

const DashboardCompetitorsRouteChildren: DashboardCompetitorsRouteChildren = {
  DashboardCompetitorsAppsRoute: DashboardCompetitorsAppsRoute,
  DashboardCompetitorsChangesRoute: DashboardCompetitorsChangesRoute,
  DashboardCompetitorsVisibilityRoute: DashboardCompetitorsVisibilityRoute,
  DashboardCompetitorsIndexRoute: DashboardCompetitorsIndexRoute,
}

const DashboardCompetitorsRouteWithChildren =
  DashboardCompetitorsRoute._addFileChildren(DashboardCompetitorsRouteChildren)

interface DashboardCreativeRouteChildren {
  DashboardCreativeChangesRoute: typeof DashboardCreativeChangesRoute
  DashboardCreativeComparisonRoute: typeof DashboardCreativeComparisonRoute
  DashboardCreativeCompetitorsRoute: typeof DashboardCreativeCompetitorsRoute
  DashboardCreativeIndexRoute: typeof DashboardCreativeIndexRoute
}

const DashboardCreativeRouteChildren: DashboardCreativeRouteChildren = {
  DashboardCreativeChangesRoute: DashboardCreativeChangesRoute,
  DashboardCreativeComparisonRoute: DashboardCreativeComparisonRoute,
  DashboardCreativeCompetitorsRoute: DashboardCreativeCompetitorsRoute,
  DashboardCreativeIndexRoute: DashboardCreativeIndexRoute,
}

const DashboardCreativeRouteWithChildren =
  DashboardCreativeRoute._addFileChildren(DashboardCreativeRouteChildren)

interface DashboardKeywordsRouteChildren {
  DashboardKeywordsCompetitorsRoute: typeof DashboardKeywordsCompetitorsRoute
  DashboardKeywordsMovementsRoute: typeof DashboardKeywordsMovementsRoute
  DashboardKeywordsResearchRoute: typeof DashboardKeywordsResearchRoute
  DashboardKeywordsTrackedRoute: typeof DashboardKeywordsTrackedRoute
  DashboardKeywordsIndexRoute: typeof DashboardKeywordsIndexRoute
  DashboardKeywordsInspectKeywordRoute: typeof DashboardKeywordsInspectKeywordRoute
}

const DashboardKeywordsRouteChildren: DashboardKeywordsRouteChildren = {
  DashboardKeywordsCompetitorsRoute: DashboardKeywordsCompetitorsRoute,
  DashboardKeywordsMovementsRoute: DashboardKeywordsMovementsRoute,
  DashboardKeywordsResearchRoute: DashboardKeywordsResearchRoute,
  DashboardKeywordsTrackedRoute: DashboardKeywordsTrackedRoute,
  DashboardKeywordsIndexRoute: DashboardKeywordsIndexRoute,
  DashboardKeywordsInspectKeywordRoute: DashboardKeywordsInspectKeywordRoute,
}

const DashboardKeywordsRouteWithChildren =
  DashboardKeywordsRoute._addFileChildren(DashboardKeywordsRouteChildren)

interface DashboardMarketsRouteChildren {
  DashboardMarketsComparisonRoute: typeof DashboardMarketsComparisonRoute
  DashboardMarketsOpportunitiesRoute: typeof DashboardMarketsOpportunitiesRoute
  DashboardMarketsRisingRoute: typeof DashboardMarketsRisingRoute
  DashboardMarketsIndexRoute: typeof DashboardMarketsIndexRoute
}

const DashboardMarketsRouteChildren: DashboardMarketsRouteChildren = {
  DashboardMarketsComparisonRoute: DashboardMarketsComparisonRoute,
  DashboardMarketsOpportunitiesRoute: DashboardMarketsOpportunitiesRoute,
  DashboardMarketsRisingRoute: DashboardMarketsRisingRoute,
  DashboardMarketsIndexRoute: DashboardMarketsIndexRoute,
}

const DashboardMarketsRouteWithChildren =
  DashboardMarketsRoute._addFileChildren(DashboardMarketsRouteChildren)

interface DashboardReviewsRouteChildren {
  DashboardReviewsCompetitorsRoute: typeof DashboardReviewsCompetitorsRoute
  DashboardReviewsRequestsRoute: typeof DashboardReviewsRequestsRoute
  DashboardReviewsSentimentRoute: typeof DashboardReviewsSentimentRoute
  DashboardReviewsIndexRoute: typeof DashboardReviewsIndexRoute
}

const DashboardReviewsRouteChildren: DashboardReviewsRouteChildren = {
  DashboardReviewsCompetitorsRoute: DashboardReviewsCompetitorsRoute,
  DashboardReviewsRequestsRoute: DashboardReviewsRequestsRoute,
  DashboardReviewsSentimentRoute: DashboardReviewsSentimentRoute,
  DashboardReviewsIndexRoute: DashboardReviewsIndexRoute,
}

const DashboardReviewsRouteWithChildren =
  DashboardReviewsRoute._addFileChildren(DashboardReviewsRouteChildren)

interface DashboardStoreRouteChildren {
  DashboardStoreCreativesRoute: typeof DashboardStoreCreativesRoute
  DashboardStoreEventsRoute: typeof DashboardStoreEventsRoute
  DashboardStoreListingRoute: typeof DashboardStoreListingRoute
  DashboardStoreLocalizationRoute: typeof DashboardStoreLocalizationRoute
  DashboardStorePublishingRoute: typeof DashboardStorePublishingRoute
  DashboardStoreIndexRoute: typeof DashboardStoreIndexRoute
}

const DashboardStoreRouteChildren: DashboardStoreRouteChildren = {
  DashboardStoreCreativesRoute: DashboardStoreCreativesRoute,
  DashboardStoreEventsRoute: DashboardStoreEventsRoute,
  DashboardStoreListingRoute: DashboardStoreListingRoute,
  DashboardStoreLocalizationRoute: DashboardStoreLocalizationRoute,
  DashboardStorePublishingRoute: DashboardStorePublishingRoute,
  DashboardStoreIndexRoute: DashboardStoreIndexRoute,
}

const DashboardStoreRouteWithChildren = DashboardStoreRoute._addFileChildren(
  DashboardStoreRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAiRoute: typeof DashboardAiRouteWithChildren
  DashboardCompetitorsRoute: typeof DashboardCompetitorsRouteWithChildren
  DashboardCreativeRoute: typeof DashboardCreativeRouteWithChildren
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardKeywordsRoute: typeof DashboardKeywordsRouteWithChildren
  DashboardMarketsRoute: typeof DashboardMarketsRouteWithChildren
  DashboardReviewsRoute: typeof DashboardReviewsRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStoreRoute: typeof DashboardStoreRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiRoute: DashboardAiRouteWithChildren,
  DashboardCompetitorsRoute: DashboardCompetitorsRouteWithChildren,
  DashboardCreativeRoute: DashboardCreativeRouteWithChildren,
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardKeywordsRoute: DashboardKeywordsRouteWithChildren,
  DashboardMarketsRoute: DashboardMarketsRouteWithChildren,
  DashboardReviewsRoute: DashboardReviewsRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStoreRoute: DashboardStoreRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  UcretsizAsoAraclariRoute: UcretsizAsoAraclariRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
